/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines Code
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum Code
    {
        /// <summary>
        /// Enum WrongCurrency for value: WrongCurrency
        /// </summary>
        [EnumMember(Value = "WrongCurrency")]
        WrongCurrency = 1,

        /// <summary>
        /// Enum CurrencyNotFound for value: CurrencyNotFound
        /// </summary>
        [EnumMember(Value = "CurrencyNotFound")]
        CurrencyNotFound = 2,

        /// <summary>
        /// Enum Unauthenticated for value: Unauthenticated
        /// </summary>
        [EnumMember(Value = "Unauthenticated")]
        Unauthenticated = 3,

        /// <summary>
        /// Enum GenerationError for value: GenerationError
        /// </summary>
        [EnumMember(Value = "GenerationError")]
        GenerationError = 4,

        /// <summary>
        /// Enum CreateError for value: CreateError
        /// </summary>
        [EnumMember(Value = "CreateError")]
        CreateError = 5

    }

}
