/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// OrdersGetViewModel
    /// </summary>
    [DataContract(Name = "OrdersGetViewModel")]
    public partial class OrdersGetViewModel : IEquatable<OrdersGetViewModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="OrdersGetViewModel" /> class.
        /// </summary>
        /// <param name="sell">sell.</param>
        /// <param name="buy">buy.</param>
        public OrdersGetViewModel(List<OrderViewModel> sell = default(List<OrderViewModel>), List<OrderViewModel> buy = default(List<OrderViewModel>))
        {
            this.Sell = sell;
            this.Buy = buy;
        }

        /// <summary>
        /// Gets or Sets Sell
        /// </summary>
        [DataMember(Name = "sell", EmitDefaultValue = true)]
        public List<OrderViewModel> Sell { get; set; }

        /// <summary>
        /// Gets or Sets Buy
        /// </summary>
        [DataMember(Name = "buy", EmitDefaultValue = true)]
        public List<OrderViewModel> Buy { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class OrdersGetViewModel {\n");
            sb.Append("  Sell: ").Append(Sell).Append("\n");
            sb.Append("  Buy: ").Append(Buy).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as OrdersGetViewModel);
        }

        /// <summary>
        /// Returns true if OrdersGetViewModel instances are equal
        /// </summary>
        /// <param name="input">Instance of OrdersGetViewModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(OrdersGetViewModel input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Sell == input.Sell ||
                    this.Sell != null &&
                    input.Sell != null &&
                    this.Sell.SequenceEqual(input.Sell)
                ) && 
                (
                    this.Buy == input.Buy ||
                    this.Buy != null &&
                    input.Buy != null &&
                    this.Buy.SequenceEqual(input.Buy)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Sell != null)
                    hashCode = hashCode * 59 + this.Sell.GetHashCode();
                if (this.Buy != null)
                    hashCode = hashCode * 59 + this.Buy.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
