/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// PostWithdrawRequestResult
    /// </summary>
    [DataContract(Name = "PostWithdrawRequestResult")]
    public partial class PostWithdrawRequestResult : IEquatable<PostWithdrawRequestResult>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostWithdrawRequestResult" /> class.
        /// </summary>
        /// <param name="success">success.</param>
        /// <param name="withdrawRequest">withdrawRequest.</param>
        /// <param name="errorCode">errorCode.</param>
        public PostWithdrawRequestResult(bool success = default(bool), WithdrawRequest withdrawRequest = default(WithdrawRequest), BalanceErrorCode errorCode = default(BalanceErrorCode))
        {
            this.Success = success;
            this.WithdrawRequest = withdrawRequest;
            this.ErrorCode = errorCode;
        }

        /// <summary>
        /// Gets or Sets Success
        /// </summary>
        [DataMember(Name = "success", EmitDefaultValue = false)]
        public bool Success { get; set; }

        /// <summary>
        /// Gets or Sets WithdrawRequest
        /// </summary>
        [DataMember(Name = "withdrawRequest", EmitDefaultValue = false)]
        public WithdrawRequest WithdrawRequest { get; set; }

        /// <summary>
        /// Gets or Sets ErrorCode
        /// </summary>
        [DataMember(Name = "errorCode", EmitDefaultValue = false)]
        public BalanceErrorCode ErrorCode { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PostWithdrawRequestResult {\n");
            sb.Append("  Success: ").Append(Success).Append("\n");
            sb.Append("  WithdrawRequest: ").Append(WithdrawRequest).Append("\n");
            sb.Append("  ErrorCode: ").Append(ErrorCode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PostWithdrawRequestResult);
        }

        /// <summary>
        /// Returns true if PostWithdrawRequestResult instances are equal
        /// </summary>
        /// <param name="input">Instance of PostWithdrawRequestResult to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PostWithdrawRequestResult input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Success == input.Success ||
                    this.Success.Equals(input.Success)
                ) && 
                (
                    this.WithdrawRequest == input.WithdrawRequest ||
                    (this.WithdrawRequest != null &&
                    this.WithdrawRequest.Equals(input.WithdrawRequest))
                ) && 
                (
                    this.ErrorCode == input.ErrorCode ||
                    (this.ErrorCode != null &&
                    this.ErrorCode.Equals(input.ErrorCode))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = hashCode * 59 + this.Success.GetHashCode();
                if (this.WithdrawRequest != null)
                    hashCode = hashCode * 59 + this.WithdrawRequest.GetHashCode();
                if (this.ErrorCode != null)
                    hashCode = hashCode * 59 + this.ErrorCode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
