/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines SignUpResponseResult
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum SignUpResponseResult
    {
        /// <summary>
        /// Enum BadInput for value: BadInput
        /// </summary>
        [EnumMember(Value = "BadInput")]
        BadInput = 1,

        /// <summary>
        /// Enum FailCreation for value: FailCreation
        /// </summary>
        [EnumMember(Value = "FailCreation")]
        FailCreation = 2,

        /// <summary>
        /// Enum SuccessEmailSent for value: SuccessEmailSent
        /// </summary>
        [EnumMember(Value = "SuccessEmailSent")]
        SuccessEmailSent = 3

    }

}
