/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// Defines TwoStepVerificationTypes
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TwoStepVerificationTypes
    {
        /// <summary>
        /// Enum BITFLEX for value: BITFLEX
        /// </summary>
        [EnumMember(Value = "BITFLEX")]
        BITFLEX = 1,

        /// <summary>
        /// Enum Google for value: Google
        /// </summary>
        [EnumMember(Value = "Google")]
        Google = 2

    }

}
