/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApiGetDepositsWitdrawals
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiGetDepositsWitdrawalsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiGetDepositsWitdrawals
        //private ApiGetDepositsWitdrawals instance;

        public ApiGetDepositsWitdrawalsTests()
        {
            // TODO uncomment below to create an instance of ApiGetDepositsWitdrawals
            //instance = new ApiGetDepositsWitdrawals();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiGetDepositsWitdrawals
        /// </summary>
        [Fact]
        public void ApiGetDepositsWitdrawalsInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiGetDepositsWitdrawals
            //Assert.IsType<ApiGetDepositsWitdrawals>(instance);
        }


        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'BlockExURL'
        /// </summary>
        [Fact]
        public void BlockExURLTest()
        {
            // TODO unit test for the property 'BlockExURL'
        }
        /// <summary>
        /// Test the property 'TxId'
        /// </summary>
        [Fact]
        public void TxIdTest()
        {
            // TODO unit test for the property 'TxId'
        }
        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Fact]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'Pending'
        /// </summary>
        [Fact]
        public void PendingTest()
        {
            // TODO unit test for the property 'Pending'
        }

    }

}
