/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApiGetOrders
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiGetOrdersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiGetOrders
        //private ApiGetOrders instance;

        public ApiGetOrdersTests()
        {
            // TODO uncomment below to create an instance of ApiGetOrders
            //instance = new ApiGetOrders();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiGetOrders
        /// </summary>
        [Fact]
        public void ApiGetOrdersInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiGetOrders
            //Assert.IsType<ApiGetOrders>(instance);
        }


        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }
        /// <summary>
        /// Test the property 'PairName'
        /// </summary>
        [Fact]
        public void PairNameTest()
        {
            // TODO unit test for the property 'PairName'
        }
        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'AmountLeft'
        /// </summary>
        [Fact]
        public void AmountLeftTest()
        {
            // TODO unit test for the property 'AmountLeft'
        }
        /// <summary>
        /// Test the property 'TradeType'
        /// </summary>
        [Fact]
        public void TradeTypeTest()
        {
            // TODO unit test for the property 'TradeType'
        }
        /// <summary>
        /// Test the property 'OrderType'
        /// </summary>
        [Fact]
        public void OrderTypeTest()
        {
            // TODO unit test for the property 'OrderType'
        }
        /// <summary>
        /// Test the property 'IsMargin'
        /// </summary>
        [Fact]
        public void IsMarginTest()
        {
            // TODO unit test for the property 'IsMargin'
        }
        /// <summary>
        /// Test the property 'LiquidationPrice'
        /// </summary>
        [Fact]
        public void LiquidationPriceTest()
        {
            // TODO unit test for the property 'LiquidationPrice'
        }
        /// <summary>
        /// Test the property 'InitialPrice'
        /// </summary>
        [Fact]
        public void InitialPriceTest()
        {
            // TODO unit test for the property 'InitialPrice'
        }
        /// <summary>
        /// Test the property 'Leverage'
        /// </summary>
        [Fact]
        public void LeverageTest()
        {
            // TODO unit test for the property 'Leverage'
        }
        /// <summary>
        /// Test the property 'InitialAmount'
        /// </summary>
        [Fact]
        public void InitialAmountTest()
        {
            // TODO unit test for the property 'InitialAmount'
        }
        /// <summary>
        /// Test the property 'StopLossPrice'
        /// </summary>
        [Fact]
        public void StopLossPriceTest()
        {
            // TODO unit test for the property 'StopLossPrice'
        }
        /// <summary>
        /// Test the property 'TakeProfitPrice'
        /// </summary>
        [Fact]
        public void TakeProfitPriceTest()
        {
            // TODO unit test for the property 'TakeProfitPrice'
        }

    }

}
