/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApiMarket
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiMarketTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiMarket
        //private ApiMarket instance;

        public ApiMarketTests()
        {
            // TODO uncomment below to create an instance of ApiMarket
            //instance = new ApiMarket();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiMarket
        /// </summary>
        [Fact]
        public void ApiMarketInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiMarket
            //Assert.IsType<ApiMarket>(instance);
        }


        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Pairs'
        /// </summary>
        [Fact]
        public void PairsTest()
        {
            // TODO unit test for the property 'Pairs'
        }

    }

}
