/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ApiPair
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ApiPairTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ApiPair
        //private ApiPair instance;

        public ApiPairTests()
        {
            // TODO uncomment below to create an instance of ApiPair
            //instance = new ApiPair();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ApiPair
        /// </summary>
        [Fact]
        public void ApiPairInstanceTest()
        {
            // TODO uncomment below to test "IsType" ApiPair
            //Assert.IsType<ApiPair>(instance);
        }


        /// <summary>
        /// Test the property 'Pair'
        /// </summary>
        [Fact]
        public void PairTest()
        {
            // TODO unit test for the property 'Pair'
        }
        /// <summary>
        /// Test the property 'Symbol'
        /// </summary>
        [Fact]
        public void SymbolTest()
        {
            // TODO unit test for the property 'Symbol'
        }
        /// <summary>
        /// Test the property 'Leverage'
        /// </summary>
        [Fact]
        public void LeverageTest()
        {
            // TODO unit test for the property 'Leverage'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
