/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ClientInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ClientInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ClientInfo
        //private ClientInfo instance;

        public ClientInfoTests()
        {
            // TODO uncomment below to create an instance of ClientInfo
            //instance = new ClientInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ClientInfo
        /// </summary>
        [Fact]
        public void ClientInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" ClientInfo
            //Assert.IsType<ClientInfo>(instance);
        }


        /// <summary>
        /// Test the property 'String'
        /// </summary>
        [Fact]
        public void StringTest()
        {
            // TODO unit test for the property 'String'
        }
        /// <summary>
        /// Test the property 'Os'
        /// </summary>
        [Fact]
        public void OsTest()
        {
            // TODO unit test for the property 'Os'
        }
        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }
        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }
        /// <summary>
        /// Test the property 'Ua'
        /// </summary>
        [Fact]
        public void UaTest()
        {
            // TODO unit test for the property 'Ua'
        }

    }

}
