/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ConfirmPermissionSignIn
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfirmPermissionSignInTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfirmPermissionSignIn
        //private ConfirmPermissionSignIn instance;

        public ConfirmPermissionSignInTests()
        {
            // TODO uncomment below to create an instance of ConfirmPermissionSignIn
            //instance = new ConfirmPermissionSignIn();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfirmPermissionSignIn
        /// </summary>
        [Fact]
        public void ConfirmPermissionSignInInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfirmPermissionSignIn
            //Assert.IsType<ConfirmPermissionSignIn>(instance);
        }


        /// <summary>
        /// Test the property 'ConfirmStatus'
        /// </summary>
        [Fact]
        public void ConfirmStatusTest()
        {
            // TODO unit test for the property 'ConfirmStatus'
        }
        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

    }

}
