/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing DepositAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DepositAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DepositAddress
        //private DepositAddress instance;

        public DepositAddressTests()
        {
            // TODO uncomment below to create an instance of DepositAddress
            //instance = new DepositAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DepositAddress
        /// </summary>
        [Fact]
        public void DepositAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" DepositAddress
            //Assert.IsType<DepositAddress>(instance);
        }


        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'DepositTag'
        /// </summary>
        [Fact]
        public void DepositTagTest()
        {
            // TODO unit test for the property 'DepositTag'
        }

    }

}
