/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Device
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeviceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Device
        //private Device instance;

        public DeviceTests()
        {
            // TODO uncomment below to create an instance of Device
            //instance = new Device();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Device
        /// </summary>
        [Fact]
        public void DeviceInstanceTest()
        {
            // TODO uncomment below to test "IsType" Device
            //Assert.IsType<Device>(instance);
        }


        /// <summary>
        /// Test the property 'IsSpider'
        /// </summary>
        [Fact]
        public void IsSpiderTest()
        {
            // TODO unit test for the property 'IsSpider'
        }
        /// <summary>
        /// Test the property 'Brand'
        /// </summary>
        [Fact]
        public void BrandTest()
        {
            // TODO unit test for the property 'Brand'
        }
        /// <summary>
        /// Test the property 'Family'
        /// </summary>
        [Fact]
        public void FamilyTest()
        {
            // TODO unit test for the property 'Family'
        }
        /// <summary>
        /// Test the property 'Model'
        /// </summary>
        [Fact]
        public void ModelTest()
        {
            // TODO unit test for the property 'Model'
        }

    }

}
