/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing FinishTier1VerificationModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FinishTier1VerificationModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FinishTier1VerificationModel
        //private FinishTier1VerificationModel instance;

        public FinishTier1VerificationModelTests()
        {
            // TODO uncomment below to create an instance of FinishTier1VerificationModel
            //instance = new FinishTier1VerificationModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FinishTier1VerificationModel
        /// </summary>
        [Fact]
        public void FinishTier1VerificationModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" FinishTier1VerificationModel
            //Assert.IsType<FinishTier1VerificationModel>(instance);
        }


        /// <summary>
        /// Test the property 'PhoneNumber'
        /// </summary>
        [Fact]
        public void PhoneNumberTest()
        {
            // TODO unit test for the property 'PhoneNumber'
        }
        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }

    }

}
