/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetAddressResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetAddressResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetAddressResponse
        //private GetAddressResponse instance;

        public GetAddressResponseTests()
        {
            // TODO uncomment below to create an instance of GetAddressResponse
            //instance = new GetAddressResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetAddressResponse
        /// </summary>
        [Fact]
        public void GetAddressResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetAddressResponse
            //Assert.IsType<GetAddressResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'Address'
        /// </summary>
        [Fact]
        public void AddressTest()
        {
            // TODO unit test for the property 'Address'
        }
        /// <summary>
        /// Test the property 'IsAddressGenerated'
        /// </summary>
        [Fact]
        public void IsAddressGeneratedTest()
        {
            // TODO unit test for the property 'IsAddressGenerated'
        }
        /// <summary>
        /// Test the property 'Currency'
        /// </summary>
        [Fact]
        public void CurrencyTest()
        {
            // TODO unit test for the property 'Currency'
        }
        /// <summary>
        /// Test the property 'Fullname'
        /// </summary>
        [Fact]
        public void FullnameTest()
        {
            // TODO unit test for the property 'Fullname'
        }
        /// <summary>
        /// Test the property 'TotalAmount'
        /// </summary>
        [Fact]
        public void TotalAmountTest()
        {
            // TODO unit test for the property 'TotalAmount'
        }
        /// <summary>
        /// Test the property 'AvailableAmount'
        /// </summary>
        [Fact]
        public void AvailableAmountTest()
        {
            // TODO unit test for the property 'AvailableAmount'
        }
        /// <summary>
        /// Test the property 'ConfirmationCount'
        /// </summary>
        [Fact]
        public void ConfirmationCountTest()
        {
            // TODO unit test for the property 'ConfirmationCount'
        }
        /// <summary>
        /// Test the property 'DestinationTag'
        /// </summary>
        [Fact]
        public void DestinationTagTest()
        {
            // TODO unit test for the property 'DestinationTag'
        }
        /// <summary>
        /// Test the property 'CurrencyType'
        /// </summary>
        [Fact]
        public void CurrencyTypeTest()
        {
            // TODO unit test for the property 'CurrencyType'
        }
        /// <summary>
        /// Test the property 'IsManual'
        /// </summary>
        [Fact]
        public void IsManualTest()
        {
            // TODO unit test for the property 'IsManual'
        }
        /// <summary>
        /// Test the property 'ErrorCode'
        /// </summary>
        [Fact]
        public void ErrorCodeTest()
        {
            // TODO unit test for the property 'ErrorCode'
        }

    }

}
