/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetBalancesListResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetBalancesListResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetBalancesListResponse
        //private GetBalancesListResponse instance;

        public GetBalancesListResponseTests()
        {
            // TODO uncomment below to create an instance of GetBalancesListResponse
            //instance = new GetBalancesListResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetBalancesListResponse
        /// </summary>
        [Fact]
        public void GetBalancesListResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetBalancesListResponse
            //Assert.IsType<GetBalancesListResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Balances'
        /// </summary>
        [Fact]
        public void BalancesTest()
        {
            // TODO unit test for the property 'Balances'
        }
        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Fact]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }

    }

}
