/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetDepositsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetDepositsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetDepositsResponse
        //private GetDepositsResponse instance;

        public GetDepositsResponseTests()
        {
            // TODO uncomment below to create an instance of GetDepositsResponse
            //instance = new GetDepositsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetDepositsResponse
        /// </summary>
        [Fact]
        public void GetDepositsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetDepositsResponse
            //Assert.IsType<GetDepositsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Deposits'
        /// </summary>
        [Fact]
        public void DepositsTest()
        {
            // TODO unit test for the property 'Deposits'
        }

    }

}
