/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetVerificationLevelResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetVerificationLevelResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetVerificationLevelResponse
        //private GetVerificationLevelResponse instance;

        public GetVerificationLevelResponseTests()
        {
            // TODO uncomment below to create an instance of GetVerificationLevelResponse
            //instance = new GetVerificationLevelResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetVerificationLevelResponse
        /// </summary>
        [Fact]
        public void GetVerificationLevelResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetVerificationLevelResponse
            //Assert.IsType<GetVerificationLevelResponse>(instance);
        }


        /// <summary>
        /// Test the property 'VerificationLevel'
        /// </summary>
        [Fact]
        public void VerificationLevelTest()
        {
            // TODO unit test for the property 'VerificationLevel'
        }
        /// <summary>
        /// Test the property 'WithdrawLimits'
        /// </summary>
        [Fact]
        public void WithdrawLimitsTest()
        {
            // TODO unit test for the property 'WithdrawLimits'
        }

    }

}
