/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GetWithdrawalsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetWithdrawalsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetWithdrawalsResponse
        //private GetWithdrawalsResponse instance;

        public GetWithdrawalsResponseTests()
        {
            // TODO uncomment below to create an instance of GetWithdrawalsResponse
            //instance = new GetWithdrawalsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetWithdrawalsResponse
        /// </summary>
        [Fact]
        public void GetWithdrawalsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetWithdrawalsResponse
            //Assert.IsType<GetWithdrawalsResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Withdrawals'
        /// </summary>
        [Fact]
        public void WithdrawalsTest()
        {
            // TODO unit test for the property 'Withdrawals'
        }
        /// <summary>
        /// Test the property 'WithdrawRequests'
        /// </summary>
        [Fact]
        public void WithdrawRequestsTest()
        {
            // TODO unit test for the property 'WithdrawRequests'
        }

    }

}
