/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrderCreateResult
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderCreateResultTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderCreateResult
        //private OrderCreateResult instance;

        public OrderCreateResultTests()
        {
            // TODO uncomment below to create an instance of OrderCreateResult
            //instance = new OrderCreateResult();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderCreateResult
        /// </summary>
        [Fact]
        public void OrderCreateResultInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderCreateResult
            //Assert.IsType<OrderCreateResult>(instance);
        }


        /// <summary>
        /// Test the property 'Success'
        /// </summary>
        [Fact]
        public void SuccessTest()
        {
            // TODO unit test for the property 'Success'
        }
        /// <summary>
        /// Test the property 'ErrorMessage'
        /// </summary>
        [Fact]
        public void ErrorMessageTest()
        {
            // TODO unit test for the property 'ErrorMessage'
        }
        /// <summary>
        /// Test the property 'Order'
        /// </summary>
        [Fact]
        public void OrderTest()
        {
            // TODO unit test for the property 'Order'
        }
        /// <summary>
        /// Test the property 'Balance'
        /// </summary>
        [Fact]
        public void BalanceTest()
        {
            // TODO unit test for the property 'Balance'
        }
        /// <summary>
        /// Test the property 'Execution'
        /// </summary>
        [Fact]
        public void ExecutionTest()
        {
            // TODO unit test for the property 'Execution'
        }
        /// <summary>
        /// Test the property 'Trades'
        /// </summary>
        [Fact]
        public void TradesTest()
        {
            // TODO unit test for the property 'Trades'
        }

    }

}
