/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OrdersGetViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrdersGetViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrdersGetViewModel
        //private OrdersGetViewModel instance;

        public OrdersGetViewModelTests()
        {
            // TODO uncomment below to create an instance of OrdersGetViewModel
            //instance = new OrdersGetViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrdersGetViewModel
        /// </summary>
        [Fact]
        public void OrdersGetViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrdersGetViewModel
            //Assert.IsType<OrdersGetViewModel>(instance);
        }


        /// <summary>
        /// Test the property 'Sell'
        /// </summary>
        [Fact]
        public void SellTest()
        {
            // TODO unit test for the property 'Sell'
        }
        /// <summary>
        /// Test the property 'Buy'
        /// </summary>
        [Fact]
        public void BuyTest()
        {
            // TODO unit test for the property 'Buy'
        }

    }

}
