/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PostForgotPasswordRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostForgotPasswordRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostForgotPasswordRequest
        //private PostForgotPasswordRequest instance;

        public PostForgotPasswordRequestTests()
        {
            // TODO uncomment below to create an instance of PostForgotPasswordRequest
            //instance = new PostForgotPasswordRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostForgotPasswordRequest
        /// </summary>
        [Fact]
        public void PostForgotPasswordRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostForgotPasswordRequest
            //Assert.IsType<PostForgotPasswordRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

    }

}
