/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TradesGetViewModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TradesGetViewModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TradesGetViewModel
        //private TradesGetViewModel instance;

        public TradesGetViewModelTests()
        {
            // TODO uncomment below to create an instance of TradesGetViewModel
            //instance = new TradesGetViewModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TradesGetViewModel
        /// </summary>
        [Fact]
        public void TradesGetViewModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" TradesGetViewModel
            //Assert.IsType<TradesGetViewModel>(instance);
        }


        /// <summary>
        /// Test the property 'DateTime'
        /// </summary>
        [Fact]
        public void DateTimeTest()
        {
            // TODO unit test for the property 'DateTime'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
