/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserAdminCommand
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserAdminCommandTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserAdminCommand
        //private UserAdminCommand instance;

        public UserAdminCommandTests()
        {
            // TODO uncomment below to create an instance of UserAdminCommand
            //instance = new UserAdminCommand();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserAdminCommand
        /// </summary>
        [Fact]
        public void UserAdminCommandInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserAdminCommand
            //Assert.IsType<UserAdminCommand>(instance);
        }



    }

}
