/*
 * BITFLEX Public API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Api;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing VerifyFaceData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class VerifyFaceDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for VerifyFaceData
        //private VerifyFaceData instance;

        public VerifyFaceDataTests()
        {
            // TODO uncomment below to create an instance of VerifyFaceData
            //instance = new VerifyFaceData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VerifyFaceData
        /// </summary>
        [Fact]
        public void VerifyFaceDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" VerifyFaceData
            //Assert.IsType<VerifyFaceData>(instance);
        }


        /// <summary>
        /// Test the property 'FaceId1'
        /// </summary>
        [Fact]
        public void FaceId1Test()
        {
            // TODO unit test for the property 'FaceId1'
        }
        /// <summary>
        /// Test the property 'FaceId2'
        /// </summary>
        [Fact]
        public void FaceId2Test()
        {
            // TODO unit test for the property 'FaceId2'
        }

    }

}
